BookstoreProject/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookstoreProject.Data;
using BookstoreProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;

namespace BookstoreProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AuthorsController : Controller
    {
        #region Properties
        private readonly ApplicationDbContext _context;
        #endregion

        #region Constructor
        public AuthorsController(ApplicationDbContext context)
        {
            _context = context;
        }
        #endregion

        #region Index
        /*
         * Yazarlar listesini veritabanindan ceker ve geri dondurur.
         */
        public async Task<IActionResult> Index()
        {
            return View(await _context.Authors.ToListAsync());
        }
        #endregion

        #region Details
        /*
         * Details fonksiyonu verilen yazar idsine gore yazari bulur ve geri dondurur
         */
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }
        #endregion

        #region Create GET
        /*
         * Create fonksiyonu yazar olusturmak icin cagrildiginda Create.cshtml viewini dondurur.
         */
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        #endregion

        #region Create POST
        /*
         * Create fonksiyonu parametre olarak alinan modele gore yazari veritabanina ekler.
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Active")] Author author)
        {
            if (ModelState.IsValid)
            {
                author.Active = true;
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }
        #endregion

        #region Edit GET
        /*
         * Yazar idsine gore yazar nesnesini veritabanindan bulur ve geri dondurur.
         */
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }
        #endregion

        #region Edit POST
        /*
         * Edit fonksiyonu disaridan aldigi yazar modeline gore yazari gunceller.
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Active")] Author author)
        {
            
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }
        #endregion

        #region Delete GET
        /*
         * Bu fonksiyon parametre olarak alinan ide gore yazari bulur ve delete sayfasi dondurur.
         */
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }
        #endregion

        #region Delete POST
        /*
         * DeleteConfirmed fonksiyonu parametre olarak aldigi id bilgisine gore yazarin aktiflik durumunu aktifse pasif pasifse aktif yapar.
         */
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Author author = _context.Authors.Where(x => x.Id == id).FirstOrDefault();

            if (author != null)
            {
                author.Active = !author.Active;
                _context.Update(author);
                await _context.SaveChangesAsync();

            }
            else
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
        #endregion


        #region AuthorExists
        /*
         * bu fonksiyon yazarin varligini kontrol eder
         */
        private bool AuthorExists(int id)
        {
            return _context.Authors.Any(e => e.Id == id);
        }
        #endregion
    }
}

BookstoreProject/Controllers/BooksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookstoreProject.Data;
using BookstoreProject.Models;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Localization;

namespace BookstoreProject.Controllers
{
    // Sadece Admin rolu tanimli olan kullanicilarin bu controllerda islem yapabilmesi icin eklenmistir.
    [Authorize(Roles = "Admin")]
    public class BooksController : Controller
    {
        #region Properties
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnviroment;
        private readonly IStringLocalizer<BooksController> _localizer;
        #endregion

        #region Constructor
        public BooksController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment, IStringLocalizer<BooksController> localizer)
        {
            _context = context;
            _hostEnviroment = hostEnvironment;
            _localizer = localizer;
        }
        #endregion

        #region Index
        /*
         * Admin panelindeki kitaplar listesi sayfasi icin tum kitaplari dil,yazar ve kategorileriyle eslestirerek dondurur.
         */
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Books.Include(b => b.Author).Include(b => b.Category).Include(b => b.Language);
            return View(await applicationDbContext.ToListAsync());
        }
        #endregion

        #region Details
        /*
         * Details fonksiyonu parametre olarak alinan kitabi yazar, kategori ve dil bilgisiyle eslestirip dondurur.
         */
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Category)
                .Include(b => b.Language)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
        #endregion

        #region Create GET
        /*
         * Create fonksiyonu cagrildiginda aktif yazar, kategori ve dil listelerini cekip viewa dondurur.
         */
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Authors.Where(a => a.Active == true), "Id", "Name");
            ViewData["CategoryId"] = new SelectList(_context.Categories.Where(a => a.Active == true), "Id", "Name");
            ViewData["LanguageId"] = new SelectList(_context.Languages.Where(a => a.Active == true), "Id", "Name");
            return View();
        }
        #endregion

        #region Create POST
        /*
         * Create fonksiyonu disaridan alinan kitap modelini veritabanina ekler.
         * Alinan uc tane kitap gorselini proje altina images klasorune kaydeder.
         * Bu images klasoru altindaki gorsellerin dosya isimlerini veritabaninda tutar.
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Book book)
        {
            if (ModelState.IsValid)
            {
                if (book.MainPhotoFile == null || book.SecondPhotoFile == null || book.ThirdPhotoFile == null)
                {
                    ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name", book.AuthorId);
                    ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", book.CategoryId);
                    ViewData["LanguageId"] = new SelectList(_context.Languages, "Id", "Name", book.LanguageId);
                    ViewData["ErrorMessage"] = _localizer["ErrorMessage1"];
                    return View();
                }

                string[] imgext = new string[3];

                imgext[0] = Path.GetExtension(book.MainPhotoFile.FileName);
                imgext[1] = Path.GetExtension(book.SecondPhotoFile.FileName);
                imgext[2] = Path.GetExtension(book.ThirdPhotoFile.FileName);

                if ((imgext[0] == ".jpg" || imgext[0] == ".png") && (imgext[1] == ".jpg" || imgext[1] == ".png") && (imgext[2] == ".jpg" || imgext[2] == ".png"))
                {
                    for (int i = 0; i < 3; i++)
                    {
                        string path_name = Guid.NewGuid().ToString() + imgext[i];
                        string saveimg = Path.Combine(_hostEnviroment.WebRootPath, "images", path_name);

                        switch (i)
                        {
                            case 0:
                                book.MainPhoto = path_name;
                                using (var uploadimg = new FileStream(saveimg, FileMode.Create))
                                {
                                    await book.MainPhotoFile.CopyToAsync(uploadimg);
                                }
                                break;
                            case 1:
                                book.SecondPhoto = path_name;
                                using (var uploadimg = new FileStream(saveimg, FileMode.Create))
                                {
                                    await book.SecondPhotoFile.CopyToAsync(uploadimg);
                                }
                                break;
                            case 2:
                                book.ThirdPhoto = path_name;
                                using (var uploadimg = new FileStream(saveimg, FileMode.Create))
                                {
                                    await book.ThirdPhotoFile.CopyToAsync(uploadimg);
                                }
                                break;
                            default:
                                break;
                        }
                    }
                }


                book.CreateDate = DateTime.Now;
                book.Active = true;
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["AuthorId"] = new SelectList(_context.Authors, "Id", "Name", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", book.CategoryId);
            ViewData["LanguageId"] = new SelectList(_context.Languages, "Id", "Name", book.LanguageId);
            return View(book);
        }
        #endregion

        #region Edit GET
        /*
         * Edit fonksiyonu parametre olarak gonderilen kitap idsine gore kitabi veritabanindan bulur.
         * Yazar, kategori ve dil listelerini çekerek geri dondurur.
         */
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }

            ViewData["AuthorId"] = new SelectList(_context.Authors.Where(a => a.Active == true), "Id", "Name", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories.Where(a => a.Active == true), "Id", "Name", book.CategoryId);
            ViewData["LanguageId"] = new SelectList(_context.Languages.Where(a => a.Active == true), "Id", "Name", book.LanguageId);
            return View(book);
        }
        #endregion

        #region Edit POST
        /*
         * Edit fonksiyonu disaridan alinan kitap modeline gore veritabaninda olan kitabi gunceller.
         * Kitap icin alinan gorsellerden degistirilmis olanlari gunceller degistirilmemis olanlar ayni kalir.
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                string[] imgext = new string[3];

                imgext[0] = book.MainPhotoFile == null ? String.Empty : Path.GetExtension(book.MainPhotoFile.FileName);
                imgext[1] = book.SecondPhotoFile == null ? String.Empty : Path.GetExtension(book.SecondPhotoFile.FileName);
                imgext[2] = book.ThirdPhotoFile == null ? String.Empty : Path.GetExtension(book.ThirdPhotoFile.FileName);

                if ((imgext[0] == ".jpg" || imgext[0] == ".png" || imgext[0] == String.Empty) && (imgext[1] == ".jpg" || imgext[1] == ".png" || imgext[1] == String.Empty) && (imgext[2] == ".jpg" || imgext[2] == ".png" || imgext[2] == String.Empty))
                {
                    for (int i = 0; i < 3; i++)
                    {
                        if (imgext[i] != String.Empty)
                        {
                            string path_name = Guid.NewGuid().ToString() + imgext[i];
                            string saveimg = Path.Combine(_hostEnviroment.WebRootPath, "images", path_name);

                            switch (i)
                            {
                                case 0:
                                    book.MainPhoto = path_name;
                                    using (var uploadimg = new FileStream(saveimg, FileMode.Create))
                                    {
                                        await book.MainPhotoFile.CopyToAsync(uploadimg);
                                    }
                                    break;
                                case 1:
                                    book.SecondPhoto = path_name;
                                    using (var uploadimg = new FileStream(saveimg, FileMode.Create))
                                    {

BookstoreProject/Views/Admin/BasketDetails.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;
@model IEnumerable<BookstoreProject.Models.BasketItem>

@{
    ViewData["Title"] = localizer["Title"].Value;
}

<section class="static about-sec">
    <div class="container">
        <h1>@localizer["BasketDetails"]</h1>
        <table id="orderDetailTable" class="table table-striped table-bordered" style="width:100%;">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Book.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Book.CategoryId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Book.Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Book.AuthorId)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Book.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Book.Category.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Book.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Book.Author.Name)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>


@section scripts {
    <script>
        $(document).ready(function () {

            var currentCulture = $('#currentCalture').text();
            if (currentCulture == "en-US") {
                $('#orderDetailTable').DataTable();
            } else {
                $('#orderDetailTable').DataTable({
                    language: TurkishLanguageRule
                });
            }
        });
    </script>
}

BookstoreProject/Views/Admin/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;

@{
    ViewData["Title"] = localizer["Title"].Value;
}

<div class="container">
    <div class="row">
        <div class=" col-md-6">
            <form asp-controller="Books" asp-action="Index">
                <div class="form-group">
                    <input type="submit" value="@localizer["BookList"]" class="btn btn-block btn-primary" />
                </div>
            </form>
        </div>
        <div class=" col-md-6">
            <form asp-controller="Authors" asp-action="Index">
                <div class="form-group">
                    <input type="submit" value="@localizer["AuthorList"]" class="btn btn-block btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class=" col-md-6">
            <form asp-controller="Categories" asp-action="Index">
                <div class="form-group">
                    <input type="submit" value="@localizer["CategoryList"]" class="btn btn-block btn-primary" />
                </div>
            </form>
        </div>
        <div class=" col-md-6">
            <form asp-controller="Languages" asp-action="Index">
                <div class="form-group">
                    <input type="submit" value="@localizer["LanguageList"]" class="btn btn-block btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class=" col-md-6">
            <form asp-controller="Admin" asp-action="OrderList">
                <div class="form-group">
                    <input type="submit" value="@localizer["PendingOrders"]" class="btn btn-block btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

BookstoreProject/Views/Admin/OrderList.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;
@model IEnumerable<BookstoreProject.Models.Basket>

@{
    ViewData["Title"] = localizer["Title"].Value;
}

<section class="static about-sec">
    <div class="container">
        <h1>@localizer["PendingOrders"]</h1>
        <table id="orderTable" class="table table-striped table-bordered" style="width:100%;">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UserDetailsId)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>@localizer["Operations"]</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            <span style="margin-right:10px;">@Html.DisplayFor(modelItem => item.UserDetails.Ad)</span>
                            <span style="margin-right:10px;">@Html.DisplayFor(modelItem => item.UserDetails.Soyad)</span>
                        </td>
                        <td>
                            <span>@localizer["StatusMessage"]</span>
                        </td>
                        <td style="display:flex;">
                            <a style="padding: 5px;width: 50%;" asp-action="ChangeSituation" asp-route-id="@item.Id"><input type="submit" value="@localizer["Cargo"]" class="btn btn-block btn-primary" /></a>
                            <a style="padding: 5px;width: 50%;" asp-action="BasketDetails" asp-route-id="@item.Id"><input type="submit" value="@localizer["Details"]" class="btn btn-block btn-primary" /></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>


@section scripts {
    <script>
        $(document).ready(function () {

            var currentCulture = $('#currentCalture').text();
            if (currentCulture == "en-US") {
                $('#orderTable').DataTable();
            } else {
                $('#orderTable').DataTable({
                    language: TurkishLanguageRule
                });
            }
        });
    </script>
}