BookstoreProject/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookstoreProject.Models
{
    public class Category
    {
        public int Id { get; set; }

        [RegularExpression(@"^[a-zA-Z_ğüşıöçĞÜŞİÖÇ ]+$", ErrorMessage = "Sadece Harf Giriniz.")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "{0} En Az {2} En Fazla {1} Karakter Uzunluğunda Olmalıdır.")]
        [Required(ErrorMessage = "{0} Alan Boş Bırakılamaz")]
        [Display(Name = "İsim")]
        public string Name { get; set; }

        [Display(Name = "Aktiflik")]
        public bool Active { get; set; }
    }
}

BookstoreProject/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookstoreProject.Data;
using BookstoreProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace BookstoreProject.Controllers
{
    // Sadece Admin rolu tanimli olan kullanicilarin bu controllerda islem yapabilmesi icin eklenmistir.
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        #region Properties
        private readonly ApplicationDbContext _context;
        #endregion

        #region Constructor
        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }
        #endregion

        #region Index
        /*
         * Kategori listesini veritabanindan ceker ve geri dondurur.
         */
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }
        #endregion

        #region Details
        /*
         * Details fonksiyonu verilen kategori idsine gore kategoriyi bulur ve geri dondurur
         */
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        #endregion

        #region Create GET
        /*
         * Create fonksiyonu kategori olusturmak icin cagrildiginda Create.cshtml viewini dondurur.
         */
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        #endregion

        #region Create POST
        /*
         * Create fonksiyonu parametre olarak alinan modele gore kategoriyi veritabanina ekler.
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Active")] Category category)
        {
            if (ModelState.IsValid)
            {
                category.Active = true;
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        #endregion

        #region Edit GET
        /*
         * Kategori idsine gore kategori nesnesini veritabanindan bulur ve geri dondurur.
         */
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        #endregion

        #region Edit POST
        /*
         * Edit fonksiyonu disaridan aldigi kategori modeline gore kategoriyi gunceller.
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Active")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        #endregion

        #region Delete GET
        /*
         * Bu fonksiyon parametre olarak alinan ide gore kategoriyi bulur ve delete sayfasi dondurur.
         */
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        #endregion

        #region Delete POST
        /*
         * DeleteConfirmed fonksiyonu parametre olarak aldigi id bilgisine gore kategorinin aktiflik durumunu aktifse pasif pasifse aktif yapar.
         */
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            Category category = _context.Categories.Where(x => x.Id == id).FirstOrDefault();

            if (category != null)
            {
                category.Active = !category.Active;
                _context.Update(category);
                await _context.SaveChangesAsync();
            }
            else
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region CategoryExists
        /*
         * bu fonksiyon kategorinin varligini kontrol eder
         */
        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
        #endregion
    }
}

BookstoreProject/Views/Categories/Create.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;
@model BookstoreProject.Models.Category

@{
    ViewData["Title"] = localizer["Title"].Value;
}
<div class="container">
    <h1>@localizer["Title"]</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <input type="submit" value="@localizer["Add"]" class="btn btn-block btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <form asp-action="Index">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <input type="submit" value="@localizer["GoBackToList"]" class="btn btn-block btn-primary" />
                </div>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookstoreProject/Views/Categories/Delete.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;
@model BookstoreProject.Models.Category

@{
    ViewData["Title"] = localizer["Title"].Value;
}
<div class="container">
    @if (Model.Active == true)
    {
        <h3>@localizer["ConvertToDeactive"]</h3>

    }
    else
    {
        <h3>@localizer["ConvertToActive"]</h3>
    }

    <hr />
    <div>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
        <div class="row">
            <div class="col-md-3">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    @if (Model.Active == true)
                    {
                        <input type="submit" value="@localizer["DeactivateButton"]" class="btn btn-block btn-danger" />
                    }
                    else
                    {
                        <input type="submit" value="@localizer["ActivateButton"]" class="btn btn-block btn-danger" />
                    }
                </form>
            </div>
            <div class="col-md-3">
                <form asp-action="Index">
                    <div class="form-group">
                        <input type="submit" value="@localizer["GoBackToList"]" class="btn btn-block btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BookstoreProject/Views/Categories/Details.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;
@model BookstoreProject.Models.Category

@{
    ViewData["Title"] = localizer["Title"].Value;
}
<div class="container">
    <h1>@localizer["Title"]</h1>

    <div>

        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Active)
            </dt>
            @if (Model.Active == true)
            {
                <dt class="col-sm-10">
                    <span class="circle green"></span>
                </dt>
            }
            else
            {
                <dt class="col-sm-10">
                    <span class="circle red"></span>
                </dt>
            }
        </dl>
    </div>
    <div class="row">
        <div class="col-md-3">
            <form asp-action="Edit" method="GET" asp-route-id="@Model.Id">
                <div class="form-group">
                    <input type="submit" value="@localizer["Edit"]" class="btn btn-block btn-primary" />
                </div>
            </form>
        </div>
        <div class="col-md-3">
            <form asp-action="Index">
                <div class="form-group">
                    <input type="submit" value="@localizer["GoBackToList"]" class="btn btn-block btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

BookstoreProject/Views/Categories/Edit.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;
@model BookstoreProject.Models.Category

@{
    ViewData["Title"] = localizer["Title"].Value;
}
<div class="container">
    <h1>@localizer["Title"]</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Active"/>
                <div class="form-group">
                    <input type="submit" value="@localizer["Save"]" class="btn btn-block btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <form asp-action="Index">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <input type="submit" value="@localizer["GoBackToList"]" class="btn btn-block btn-primary" />
                </div>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookstoreProject/Views/Categories/Index.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer;
@model IEnumerable<BookstoreProject.Models.Category>

@{
    ViewData["Title"] = localizer["Title"].Value;
}

<section class="static about-sec">
    <div class="container">
        <h1>@localizer["Title"]</h1>
        <form asp-controller="Categories" asp-action="Create" style=" margin-bottom: 10px;" method="get">
            <button type="submit" class="btn btn-primary">@localizer["AddCategory"]</button>
        </form>
        <table id="categoriesTable" class="table table-striped table-bordered" style="width:100%;">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Active)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        @if (item.Active == true)
                        {
                            <td><span class="circle green"></span></td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit"></i></a>
                                <a asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle"></i></a>
                                <a asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-window-close"></i></a>
                            </td>
                        }
                        else
                        {
                            <td><span class="circle red"></span></td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit"></i></a>
                                <a asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info-circle"></i></a>
                                <a asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-check-square"></i></a>
                            </td>

                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

@section scripts {
    <script>
        $(document).ready(function () {
            var currentCulture = $('#currentCalture').text();
            if (currentCulture == "en-US") {
                $('#categoriesTable').DataTable();
            } else {
                $('#categoriesTable').DataTable({
                    language: TurkishLanguageRule
                });
            }
        });
    </script>
}